### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by roman-melnyk** [jcoleman/relation_to_struct#15]
hi! any plans on updating to support Rails 6?

**Comment by jcoleman** [comment]
Eventually yes, but no immediate timeframe since the apps I work with haven't upgraded yet.

But I'd be happy to look at PRs; if you'd like to help out with that, I'd probably start by adding 6.0 to the [list of tested versions](https://github.com/jcoleman/relation_to_struct/blob/master/Appraisals#L1) and then following the [testing instructions](https://github.com/jcoleman/relation_to_struct#contributing).

**Comment by jcoleman** [comment]
I did also noticed I missed #14, so maybe that will handle it.

**Comment by roman-melnyk** [comment]
could you please publish a new version of gem?

**Comment by jcoleman** [comment]
Pushed as 1.5.1.
